// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.base.entidades.ubicaciones;

import com.base.entidades.ubicaciones.Ubicacion;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Ubicacion_Roo_Configurable {
    
    declare @type: Ubicacion: @Configurable;
    
}
