// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.base.entidades.medicamentos;

import com.base.entidades.medicamentos.Medicamento;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Medicamento_Roo_Configurable {
    
    declare @type: Medicamento: @Configurable;
    
}
