// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.base.entidades.ubicaciones;

import com.base.entidades.ubicaciones.UbicacionPersona;
import javax.persistence.Entity;

privileged aspect UbicacionPersona_Roo_Jpa_Entity {
    
    declare @type: UbicacionPersona: @Entity;
    
}
