// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.base.entidades.instituciones;

import com.base.entidades.instituciones.TipoInstitucion;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TipoInstitucion_Roo_Configurable {
    
    declare @type: TipoInstitucion: @Configurable;
    
}
