// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.base.entidades.personas;

import com.base.entidades.personas.RelacionesALBA;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RelacionesALBA_Roo_Configurable {
    
    declare @type: RelacionesALBA: @Configurable;
    
}
