// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.base.entidades.animales;

import com.base.entidades.animales.Animal;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Animal_Roo_Configurable {
    
    declare @type: Animal: @Configurable;
    
}
