Ext.define('AM.model.Animal', {
    extend: 'Ext.data.Model',
    fields: [
    	'id', 
    	'nombre',
    	'chip',
    	'segundoIdentificador',      	
    	'raza',
    	'fechaNacimiento',
    	'sexo',
    	'esterilizado',
    	'color',
    	'tamano',
    	'propietario',
    	'fechaRegistro',
    	'descripcion',
    	'foto',
    	'lugarRecogida',
    	'recogidoAyuntamiento',
    	'personaAvisa',
    	'personaRecoge',
    	'personaRecepciona',
    	'pesoActual',
    	'fechaPesoActual',
    	'fechaUbicacionActual',
    	'especie',
		'idUbicacionActual',
		'nombreUbicacionActual',
		'institucionActual',
		'estado',
		'fechaAvisa',
		'fechaRecepcion',
		'fechaRecogido',
		'alturaCruz'
    	]
    
});